import { createStyles } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";

const useStyles = createStyles((theme) => ({
  container: {
    padding: "0rem 2rem",
    display: "flex",
    height: "100vh",
  },
}));

const Home: NextPage = () => {
  const { classes } = useStyles();
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p
        style={{
          textAlign: "center",
          margin: "auto",
        }}
      >
        A Template with Mantine and Authentication Forms Preconfigured
      </p>
    </div>
  );
};

export default Home;
